# Generated by Django 3.2.15 on 2022-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskuserrel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_url', models.URLField()),
                ('action', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quota', models.DateTimeField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
