# Generated by Django 4.1.1 on 2022-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskuserrel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitetask',
            old_name='quota',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='socialmediatask',
            old_name='quota',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='surveytask',
            old_name='quota',
            new_name='endtime',
        ),
        migrations.RemoveField(
            model_name='surveytask',
            name='individual_response_view',
        ),
        migrations.RemoveField(
            model_name='surveytask',
            name='statistics',
        ),
        migrations.AddField(
            model_name='invitetask',
            name='lock_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitetask',
            name='lock_time_boundary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitetask',
            name='qota',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='lock_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='lock_time_boundary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surveytask',
            name='lock_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surveytask',
            name='lock_time_boundary',
            field=models.IntegerField(default=1),
        ),
    ]
