# Generated by Django 4.1.1 on 2022-10-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_levelmanagement_user_levelmanagement_lvl_fee_and_more'),
        ('tasks', '0005_rename_quota_invitetask_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_task', to='user.levelmanagement'),
        ),
    ]
