# Generated by Django 4.1.1 on 2022-09-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='images/'),
        ),
    ]
