# Generated by Django 4.1.1 on 2022-10-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_grade_profile_value_alter_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="pro_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="trial_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
