# Generated by Django 4.1.1 on 2022-10-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_profile_image"),
        ("user", "0006_profile_balance_profile_pro_status_and_more"),
    ]

    operations = []
