# Generated by Django 4.1.1 on 2022-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20221022_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelmanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='levelmanagement',
            name='lvl_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='levelmanagement',
            name='lvl_tasks_no',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='levelmanagement',
            name='max_lvl_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='levelmanagement',
            name='total_lvl_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='levelmanagement',
            name='levels',
            field=models.IntegerField(default=1),
        ),
    ]
