# Generated by Django 4.1.1 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeoftrialperiod', models.IntegerField(default=0)),
                ('taskallowancetime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lane1percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lane2percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lane3percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='paymentvertfication',
            field=models.BooleanField(default=False),
        ),
    ]
